rover_ns:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Position Controllers ---------------------------------------
  # Body Rocker joints
  body_rocker_left_controller:
    type: effort_controllers/JointPositionController
    joint: "body_rocker_left"
    pid: {p: 100, i: 0.1, d: 10}
  body_rocker_right_controller:
    type: effort_controllers/JointPositionController
    joint: "body_rocker_right"
    pid: {p: 100, i: 0.1, d: 10}

  # Rocker_Bogie joints
  rocker_left_bogie_left_controller:
    type: effort_controllers/JointPositionController
    joint: "rocker_left_bogie_left"
    pid: {p: 100, i: 0.1, d: 10}
  rocker_right_bogie_right_controller:
    type: effort_controllers/JointPositionController
    joint: "rocker_right_bogie_right"
    pid: {p: 100, i: 0.1, d: 10}

  # Corner joints
  bogie_left_corner_lf_controller:
    type: effort_controllers/JointPositionController
    joint: "bogie_left_corner_lf"
    pid: {p: 1, i: 1, d: 1}
  rocker_left_corner_lb_controller:
    type: effort_controllers/JointPositionController
    joint: "rocker_left_corner_lb"
    pid: {p: 1, i: 1, d: 1}
  rocker_right_corner_rb_controller:
    type: effort_controllers/JointPositionController
    joint: rocker_right_corner_rb
    pid: {p: 1, i: 1, d: 1}
  bogie_right_corner_rf_controller:
    type: effort_controllers/JointPositionController
    joint: bogie_right_corner_rf
    pid: {p: 1, i: 1, d: 1}

  # Arm joints 
  body_arm_shoulder_1_controller:
    type: effort_controllers/JointPositionController
    joint: "body_arm_shoulder_1"
    pid: {p: 1, i: 1, d: 1}
  arm_shoulder_1_arm_shoulder_2_controller:
    type: effort_controllers/JointPositionController
    joint: "arm_shoulder_1_arm_shoulder_2"
    pid: {p: 1, i: 1, d: 1}
  arm_shoulder_2_arm_elbow_controller:
    type: effort_controllers/JointPositionController
    joint: "arm_shoulder_2_arm_elbow"
    pid: {p: 1, i: 1, d: 1}
  arm_elbow_arm_hand_left_controller:
    type: effort_controllers/JointPositionController
    joint: "arm_elbow_arm_hand_left"
    pid: {p: .05, i: 0.05, d: 0.000}
  arm_elbow_arm_hand_right_controller:
    type: effort_controllers/JointPositionController
    joint: "arm_elbow_arm_hand_right"
    pid: {p: .05, i: 0.05, d: 0.000}

  # Velocity Controllers ---------------------------------------
  # Wheels
  corner_lf_wheel_lf_controller:
    type: effort_controllers/JointVelocityController
    joint: "corner_lf_wheel_lf"
    pid: {p: .2, i: 0.05, d: 0}
  bogie_left_wheel_lm_controller:
    type: effort_controllers/JointVelocityController
    joint: "bogie_left_wheel_lm"
    pid: {p: .2, i: 0.05, d: 0}
  corner_lb_wheel_lb_controller:
    type: effort_controllers/JointVelocityController
    joint: "corner_lb_wheel_lb"
    pid: {p: .2, i: 0.05, d: 0}
  corner_rb_wheel_rb_controller:
    type: effort_controllers/JointVelocityController
    joint: "corner_rb_wheel_rb"
    pid: {p: .2, i: 0.05, d: 0}
  bogie_right_wheel_rm_controller:
    type: effort_controllers/JointVelocityController
    joint: "bogie_right_wheel_rm"
    pid: {p: .2, i: 0.05, d: 0}
  corner_rf_wheel_rf_controller:
    type: effort_controllers/JointVelocityController
    joint: "corner_rf_wheel_rf"
    pid: {p: .2, i: 0.05, d: 0}

  joint_limits:
    # Body joints
    body_rocker_left:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 100.0
      has_acceleration_limits: true
      max_acceleration: 10
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 10
    body_rocker_right: 
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 100.0
      has_acceleration_limits: true
      max_acceleration: 10
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 10 
    # Rocker Bogie joints
    rocker_left_bogie_left:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    rocker_right_bogie_right:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    # Corner joints
    bogie_left_corner_lf:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    rocker_left_corner_lb:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    bogie_right_corner_rf:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    rocker_right_corner_rb:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    # Arm joints
    body_arm_shoulder_1:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    arm_shoulder_1_arm_shoulder_2:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    arm_shoulder_2_arm_elbow:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    arm_elbow_arm_hand_left:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    arm_elbow_arm_hand_right:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    # Wheel joints
    corner_lf_wheel_lf:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    bogie_left_wheel_lm:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    corner_lb_wheel_lb:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    corner_rb_wheel_rb:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    bogie_right_wheel_rm:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5
    corner_rf_wheel_rf:
      has_position_limits: false
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: true
      max_acceleration: 1
      has_jerk_limits: true
      max_jerk: 10.0
      has_effort_limits: true
      max_effort: 0.5